service: belieff-questionaries

frameworkVersion: '2'
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: GET
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: ./.env
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY