# @baseUrl = http://localhost:8080
# @baseUrl = http://localhost:3000/dev
@baseUrl = https://egsezzx939.execute-api.us-east-1.amazonaws.com/dev/

### GET /api/profiles
GET {{baseUrl}}/api/profiles/profile-d3c6299e-d457-4194-8663-1f02942900ee
Content-Type: application/json

### POST /api/profiles
POST {{baseUrl}}/api/profiles
Content-Type: application/json

{
    "email": "ealvarez@gmail.com",
    "lastname": "AlvarezPacheco",
    "firstname": "Esteban",
    "curp": "AEPA980929HYNLCD12",
    "rfc": "AAPA9809294F2",
    "age": 18,
    "phone_number": "9991549015",
    "birthday": "1998-09-29",
    "userId": "2"
}

### POST /api/employees
POST {{baseUrl}}/api/employees
Content-Type: application/json

{
    "companyId": "company-d3c6299e-d457-4194-8663-1f02942900ed",
    "profileId": "profile-d3c6299e-d457-4194-8663-1f02942900ef"
}

### GET /api/employees/:companyId
GET {{baseUrl}}/api/employees/company-d3c6299e-d457-4194-8663-1f02942900ed
